version: '3.8'

services:
  dominios-back:
    build:
      context: ./dominios-back
      dockerfile: Dockerfile
    container_name: dominios-back
    volumes:
      - ./dominios-back:/var/www
      - /var/www/vendor
    working_dir: /var/www
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: laravel
      DB_USERNAME: root
      DB_PASSWORD: secret
    depends_on:
      - mysql
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8000:80"
    volumes:
      - ./dominios-back:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - dominios-back
    networks:
      - app-network

  dominios-front:
    build:
      context: ./dominios-front
    container_name: dominios-front
    ports:
      - "3000:3000"
    volumes:
      - ./dominios-front:/app
      - /app/node_modules
    working_dir: /app
    command: npm run dev
    depends_on:
      - dominios-back
    networks:
      - app-network

  mysql:
    image: mysql:8
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: laravel
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

volumes:
  mysql-data:

networks:
  app-network:
    driver: bridge
